<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <script> var url_base = "LinksWebsite/public/"</script>


        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->setCharset('UTF-8');
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/link-template.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.min.css')

        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/base64.js')
            ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',)); ?>

    </head>
    <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#example-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('news') ?>">IT News</a>



        </div>
        <div class="collapse navbar-collapse" id="example-navbar-collapse">
            <ul class="nav navbar-nav navbar-right" style="margin-right: 10px;">
                <li class="" >
                        <?php if($this->zfcUserIdentity()){
                            if($this->zfcUserType() == 'user') {
                                ?>
                                <a>Signed in as <?php echo $this->ZfcUserDisplayName(); ?></a>
                            <?php
                            }
                            else
                            {
                                ?>
                                <a href="<?php echo $this->url('adminpanel') ?>">[Admin panel]</a>
                                <?php
                            }
                        }
                        else
                        {
                        ?>
                    <a href="<?php echo $this->url('zfcuser/login') ?>">[<?php echo $this->translate('Sign In'); ?>]</a>
                    <?php

                        }
                        ?>

                </li>
                <li class=""">
                <?php if($this->zfcUserIdentity()){
                    ?>
                    <a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>
                <?php
                }
                else
                {
                    ?>
                    <a href="<?php echo $this->url('zfcuser/register') ?>">[<?php echo $this->translate('Register'); ?>]</a>
                <?php

                }
                ?>
                </li>


            </ul>

        </div>
    </nav>

        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> by Frosina Stamatoska <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
